version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks: 
      - mindBehindNetwork
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
    networks: 
      - mindBehindNetwork
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MindBehindDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
    - ./mysql-data:/var/lib/mysql
    networks: 
      - mindBehindNetwork
networks:
  mindBehindNetwork:
    driver: bridge
